create table tb_category (id bigint generated by default as identity, name varchar(255), primary key (id));
create table tb_product (price float(53), category_id bigint not null, id bigint generated by default as identity, description TEXT, img_url varchar(255), name varchar(255), primary key (id));
alter table if exists tb_product add constraint FK8i0sq9mfbpsrabrm2pum9fspo foreign key (category_id) references tb_category;
create table tb_category (id bigint generated by default as identity, name varchar(255), primary key (id));
create table tb_product (price float(53), category_id bigint not null, id bigint generated by default as identity, description TEXT, img_url varchar(255), name varchar(255), primary key (id));
alter table if exists tb_product add constraint FK8i0sq9mfbpsrabrm2pum9fspo foreign key (category_id) references tb_category;
